print("##############################")
print("#                            #")
print("#  Andre Cristian Nathanael  #")
print("#       2410817210006        #")
print("#                            #")
print("##############################")